### PR TITLE
Add PHP (and linux kernel)

### PR DESCRIPTION
**Pull request by kev626**
I thought this project needed more PHP.

### CODE REVIEW

**Comment by ParadauxIO** [comment]
agreed

**Comment by itsNordLord** [comment]
requires french translations

**Review by MWHunter — APPROVED** [review]
Read through all the code and it looks good

**Review by Palomox — APPROVED** [review]
Checked it. Definitely useful for the important future of assignment 1620

**Comment by tadhgboyle** [comment]
Hm

**Review by MWHunter — COMMENTED** [review]
lgtm

**Pull request closed without merging**
